import { config } from './config.js';

/** 出站追加 / 入站剥离的卡片水印（body.elements 末尾 markdown）。 */
export function buildWatermarkElement(
  botName = config.lark.botName,
  botUrl = config.lark.botUrl,
): Record<string, unknown> | undefined {
  const name = botName.trim();
  const url = botUrl.trim();
  if (!name || !url) return undefined;
  return {
    tag: 'markdown',
    content: `<font color='grey-300'>Generated by </font>[${name}](${url})`,
    text_align: 'right',
    text_size: 'x-small',
    margin: '0px 0px 0px 0px',
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function bodyElements(card: Record<string, unknown>): unknown[] | undefined {
  const body = card.body;
  if (!isRecord(body) || !Array.isArray(body.elements)) return undefined;
  return body.elements;
}

/** 是否为本机器人追加的水印（用 URL / Generated by 指纹识别）。 */
export function isWatermarkElement(
  el: unknown,
  botUrl = config.lark.botUrl,
): boolean {
  if (!isRecord(el) || el.tag !== 'markdown') return false;
  if (typeof el.content !== 'string') return false;
  const content = el.content;
  if (!content.includes('Generated by')) return false;
  const url = botUrl.trim();
  if (url && content.includes(url)) return true;
  // 未配置 URL：用右对齐小字 + Generated by 链接结构兜底
  if (el.text_align !== 'right' || el.text_size !== 'x-small') return false;
  return /Generated by[\s\S]*\[[^\]]+\]\(https?:\/\/[^)]+\)/.test(content);
}

/**
 * 出站前追加水印。已有则先剥离再追加，保证幂等；
 * 缺少 botName/botUrl 时原样返回。
 */
export function appendCardWatermark(
  card: Record<string, unknown>,
): Record<string, unknown> {
  const watermark = buildWatermarkElement();
  if (!watermark) return card;

  const next = structuredClone(card) as Record<string, unknown>;
  const elements = bodyElements(next);
  if (!elements) return next;

  while (elements.length > 0 && isWatermarkElement(elements[elements.length - 1])) {
    elements.pop();
  }
  elements.push(watermark);
  return next;
}

/**
 * 入站先去水印，再交给模型 / 底稿 / 改卡逻辑。
 * 原地修改；无 body.elements 或无水印时为 no-op。
 */
export function stripCardWatermark(card: Record<string, unknown>): void {
  const elements = bodyElements(card);
  if (!elements) return;
  while (elements.length > 0 && isWatermarkElement(elements[elements.length - 1])) {
    elements.pop();
  }
}
